### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by lktidaohuoxing** [engcang/vins-fusion-gpu-no-ros#1]
Hello, Nice job，  I want to ask, is this code workable? Or are you preparing?

**Comment by engcang** [comment]
Hi @lktidaohuoxing . The code works! If you are suffering from any problems with it, tell me~

**Comment by lktidaohuoxing** [comment]
Hi, 
thanks for your quick reply, I don't know what your camera type: MEI is, I have a segment fault when loading parameters. I found the problem in **tool.cpp featureTracker.readIntrinsicParameter(CAM_NAMES)** Is it my parameter problem?
My command is:
`` ./vins_estimator/build/vins_estimator ./config/mono.yaml ../../../dataset/EUROC/MH_01_easy/mav0/cam0/data/ ./euroc_data_timestamp/MH01.txt ../ ../../dataset/EUROC/MH_01_easy/mav0/imu0/data.csv 
``

**Comment by lktidaohuoxing** [comment]
Thank you for your reply, the problem has been solved inexplicably, it is caused by the difference of opencv version.

**Comment by engcang** [comment]
Good to hear that you solved the problem! and yes the OpenCV version should be around 3.4 as far as I remember correctly.
