### ISSUE TITLE
Is it possible to run this code on a platform without GPU?

### ISSUE THREAD

**Issue by zxytql** [engcang/vins-fusion-gpu-no-ros#2]
Hello! 
I really appreciate that you guys have done such a great job! I'm new to SLAM and I'm trying to run VINS-Fusion on my computer without using ros and GPU. Is it possible to run this code on a platform without GPU? Or how can I do to remove the dependency of GPU?

**Comment by engcang** [comment]
@zxytql Hi.

This repository uses same config file as original repository, there are two GPU related parameters in config file - https://github.com/pjrambo/VINS-Fusion-gpu/blob/master/config/euroc/euroc_stereo_imu_config.yaml#L43-L44

So, all the related lines in the code should be deleted like - 
https://github.com/engcang/vins-fusion-gpu-no-ros/blob/master/vins_estimator/include/tools.h#L38-L40
https://github.com/engcang/vins-fusion-gpu-no-ros/blob/master/vins_estimator/src/tools.cpp#L3214-L3297
https://github.com/engcang/vins-fusion-gpu-no-ros/blob/master/vins_estimator/src/tools.cpp#L3346-L3374

**Comment by zxytql** [comment]
> @zxytql Hi.
> 
> This repository uses same config file as original repository, there are two GPU related parameters in config file - https://github.com/pjrambo/VINS-Fusion-gpu/blob/master/config/euroc/euroc_stereo_imu_config.yaml#L43-L44
> 
> So, all the related lines in the code should be deleted like - https://github.com/engcang/vins-fusion-gpu-no-ros/blob/master/vins_estimator/include/tools.h#L38-L40 https://github.com/engcang/vins-fusion-gpu-no-ros/blob/master/vins_estimator/src/tools.cpp#L3214-L3297 https://github.com/engcang/vins-fusion-gpu-no-ros/blob/master/vins_estimator/src/tools.cpp#L3346-L3374

Thanks so much! I make it through!!

**Comment by zxytql** [comment]
Hi @engcang , I'm facing another problem.
Everything is ok when I test it with the EuroC dataset, but things going down when I using my own dataset.
My dataset is a littile different with EuroC and the pixels of the picture are 1280 x 720.
For example, the format of timestamp in EuroC is like `1403636579763555584`, `1403636580163555584` while the format of timestamp in my dataset is like `12824.450805`, `12824.920685`. So I have to edit the `main.cpp` file in `vins_estimator` to adapt this change. 
```c
void LoadImages(const string &strImagePath, const string &strTimesStampsPath,
                vector<string> &strImagesFileNames, vector<double> &timeStamps)
{
    ifstream fTimes;
    fTimes.open(strTimesStampsPath.c_str());
    timeStamps.reserve(5000); // reserve vector space
    strImagesFileNames.reserve(5000);
    while (!fTimes.eof())
    {
        string s;
        getline(fTimes, s);
        if (!s.empty())
        {
            stringstream ss;
            ss << s;
            strImagesFileNames.push_back(strImagePath + "/" + ss.str() + ".png"); //@zxytql
            double t;
            ss >> t;
#ifdef EUROC_DATA
            timeStamps.push_back(t / 1e9);
#elif defined(MY_DATA)
            timeStamps.push_back(t);
#endif
        }
    }
}
```
...and some other places in `main.cpp`. I haven't edit the `tools.cpp` in `vins_estimator`.
I recomplie the code and run it. It looks good and it show the tracked image with dotts and arrows.
But after about 20 seconds, error occurs:
```shell
n_pts size: 1
n_pts size: 1
n_pts size: 2
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0418 18:35:13.934111 118594 parameter_block.h:331] Manifold::PlusJacobian computation returned an invalid matrix for x: -nan -nan -nan -nan
 Jacobian matrix : 0nan 0nan 0nan
-nan -nan 0nan
0nan -nan -nan
-nan 0nan -nan
F0418 18:35:13.934191 118594 parameter_block.h:186] Check failed: UpdatePlusJacobian() Manifold::PlusJacobian computation failed for x: -nan -nan -nan -nan
*** Check failure stack trace: ***
已放弃（核心已转储）
```
Do you have any idea about this problem? Thanks!

**Comment by zxytql** [comment]
> Hi @engcang , I'm facing another problem.
> 
> Everything is ok when I test it with the EuroC dataset, but things going down when I using my own dataset.
> 
> My dataset is a littile different with EuroC and the pixels of the picture are 1280 x 720.
> 
> For example, the format of timestamp in EuroC is like `1403636579763555584`, `1403636580163555584` while the format of timestamp in my dataset is like `12824.450805`, `12824.920685`. So I have to edit the `main.cpp` file in `vins_estimator` to adapt this change. 
> 
> ```c
> 
> void LoadImages(const string &strImagePath, const string &strTimesStampsPath,
> 
>                 vector<string> &strImagesFileNames, vector<double> &timeStamps)
> 
> {
> 
>     ifstream fTimes;
> 
>     fTimes.open(strTimesStampsPath.c_str());
> 
>     timeStamps.reserve(5000); // reserve vector space
> 
>     strImagesFileNames.reserve(5000);
> 
>     while (!fTimes.eof())
> 
>     {
> 
>         string s;
> 
>         getline(fTimes, s);
> 
>         if (!s.empty())
> 
>         {
> 
>             stringstream ss;
> 
>             ss << s;
> 
>             strImagesFileNames.push_back(strImagePath + "/" + ss.str() + ".png"); //@zxytql
> 
>             double t;
> 
>             ss >> t;
> 
> #ifdef EUROC_DATA
> 
>             timeStamps.push_back(t / 1e9);
> 
> #elif defined(MY_DATA)
> 
>             timeStamps.push_back(t);
> 
> #endif
> 
>         }
> 
>     }
> 
> }
> 
> ```
> 
> ...and some other places in `main.cpp`. I haven't edit the `tools.cpp` in `vins_estimator`.
> 
> I recomplie the code and run it. It looks good and it show the tracked image with dotts and arrows.
> 
> But after about 20 seconds, error occurs:
> 
> ```shell
> 
> n_pts size: 1
> 
> n_pts size: 1
> 
> n_pts size: 2
> 
> WARNING: Logging before InitGoogleLogging() is written to STDERR
> 
> W0418 18:35:13.934111 118594 parameter_block.h:331] Manifold::PlusJacobian computation returned an invalid matrix for x: -nan -nan -nan -nan
> 
>  Jacobian matrix : 0nan 0nan 0nan
> 
> -nan -nan 0nan
> 
> 0nan -nan -nan
> 
> -nan 0nan -nan
> 
> F0418 18:35:13.934191 118594 parameter_block.h:186] Check failed: UpdatePlusJacobian() Manifold::PlusJacobian computation failed for x: -nan -nan -nan -nan
> 
> *** Check failure stack trace: ***
> 
> 已放弃（核心已转储）
> 
> ```
> 
> Do you have any idea about this problem? Thanks!

I have solved this problem by change the size of pictures into 640×480. But I still have no idea about how it appears.
